# global configs
Global:
  task_type: Classification
  train_loop: ClassificationTrainingEpochLoop
  validate_loop: ClassificationEvaluationLoop
  checkpoint: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 1
  max_num_latest_checkpoint: 0
  eval_during_train: True
  eval_interval: 1
  eval_unit: "epoch"
  accum_steps: 1
  epochs: 90
  print_batch_step: 10
  use_visualdl: False
  seed: 2023


DistributedStrategy:
  data_parallel: True

# model architecture
Model:
  name: simsiam_lp

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
  Eval:
    - CELoss:
        weight: 1.0

LRScheduler:
    name: TimmCosine
    learning_rate: 1.6
    eta_min: 0.0
    warmup_epoch: 0
    warmup_start_lr: 0.0
    decay_unit: epoch
    warmup_prefix: False
    last_epoch: 0

Optimizer:
  name: MomentumLARS
  momentum: 0.9
  weight_decay: 0.0

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageFolder
      root: ./dataset/ILSVRC2012/train
      transform:
        - RandomResizedCrop:
            size: 224
        - RandomHorizontalFlip:
        - ToTensor:
        - Normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    sampler:
      name: DistributedBatchSampler
      batch_size: 512
      drop_last: True
      shuffle: True
    loader:
      num_workers: 8
      use_shared_memory: True

  Eval:
    dataset:
      name: ImageFolder
      root: ./dataset/ILSVRC2012/val
      transform:
        - Resize:
            size: 256
            backend: pil
        - CenterCrop:
            size: 224
        - ToTensor:
        - Normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    sampler:
      name: DistributedBatchSampler
      batch_size: 512
      drop_last: False
      shuffle: False
    loader:
      num_workers: 8
      use_shared_memory: True

Metric:
  Eval:
    - TopkAcc:
        topk: [1, 5]

Export:
  export_type: paddle
  input_shape: [None, 3, 224, 224]
